rest:
    resource: "@And6aTrombiBundle/Controller/RestController.php"
    prefix: /rest
    type: annotation

And6aUserBundle:
    resource: "@And6aUserBundle/Resources/config/routing.yml"
    prefix:   /

And6aTrombiBundle:
    resource: "@And6aTrombiBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: And6aTrombiBundle:Default:index }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
