_welcome:
    pattern:  /
    defaults: { _controller: And6aTrombiBundle:Default:index }

And6aTrombiBundle:
    resource: "@And6aTrombiBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
