# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

And6aUserBundle_contact:
    resource: "routing/contact.php"
    prefix: /contact

And6aTrombiBundle_groups:
    resource: "routing/groupsuser.yml"
    prefix: /groups

#And6aUserBundle_groups:
#    resource: "routing/groups.yml"
#    prefix: /groups

And6aUserBundle_user_change_avatar:
    pattern:  /profile/avatar
    defaults: { _controller: And6aUserBundle:Default:avatar }